DEVICE_CONFIG_TIMER_FD		400
DEBUG_FUNC_ENABLE_FT		1
DEBUG_FUNC_ENABLE_BT		1
DEBUG_FUNC_ENABLE_PROF		1
DEBUG_FUNC_ENABLE_WATCH		1
DEBUG_FUNC_ENABLE_SKIP_CLOCK    1
DEBUG_FUNC_ENABLE_SYNC_TIME	0
#DEBUG_FUNC_SHOW_SKIP_TIME	1
DEBUG_FUNC_ENABLE_VDEV		1
DEBUG_FUNC_VDEV_TX_PORTNO   	{{UNITY_PORTNO}}
DEBUG_FUNC_VDEV_TX_IPADDR	{{UNITY_IP_ADDR}}
DEBUG_FUNC_VDEV_RX_IPADDR  	{{ATHRILL_IP_ADDR}}
DEBUG_FUNC_VDEV_RX_PORTNO  	{{ATHRILL_PORTNO}}

